### ISSUE TITLE
Maximum update depth exceeded

### ISSUE THREAD

**Issue by esxmod** [esxmod/KoSA-demo-client#2]
The following error occurs when moving a menu with mobile layout applied:

```log
react-dom.production.min.js:189 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at nc (react-dom.production.min.js:266:249)
    at nl (react-dom.production.min.js:181:441)
    at onVisibleChange (Menu.js:390:7)
    at se (Overflow.js:151:73)
    at Overflow.js:225:11
    at ru (react-dom.production.min.js:244:332)
    at wu (react-dom.production.min.js:261:147)
    at bu (react-dom.production.min.js:260:446)
    at yu (react-dom.production.min.js:259:431)
    at react-dom.production.min.js:283:96
```

https://reactjs.org/docs/error-decoder.html?invariant=185

```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

**Comment by esxmod** [comment]
https://github.com/ant-design/ant-design/issues/36559#issuecomment-1196238030

**Comment by esxmod** [comment]
https://github.com/react-component/overflow/pull/24
